/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Bomberman World)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8003EE18u
#define func_8003EE18 BootEntry  /* alias */
